# **WelCome To Numpy tutorial

In [147]:
import numpy as np

In [148]:
myArr=np.array([[3,22,44345,5]], np.int64)

In [149]:
myArr

array([[    3,    22, 44345,     5]])

In [150]:
myArr[0,1].item()

22

In [151]:
myArr.shape

(1, 4)

In [152]:
myArr.dtype

dtype('int64')

In [153]:
myArr[0,3]=11

In [154]:
myArr

array([[    3,    22, 44345,    11]])

# Array Creation : Conversion from other Python Structures

In [155]:
listArray=np.array([[1,2,3],[5,5,6],[7,8,9]])

In [156]:
listArray

array([[1, 2, 3],
       [5, 5, 6],
       [7, 8, 9]])

In [157]:
listArray.dtype

dtype('int64')

In [158]:
listArray.shape

(3, 3)

In [159]:
listArray.size

9

In [160]:
listArray[0,2]=78

In [161]:
listArray

array([[ 1,  2, 78],
       [ 5,  5,  6],
       [ 7,  8,  9]])

In [162]:
np.array({33,44,55})

array({33, 44, 55}, dtype=object)

In [163]:
zeros=np.zeros((2,5))

In [164]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [165]:
zeros.shape

(2, 5)

In [166]:
zeros.dtype

dtype('float64')

In [167]:
rnge=np.arange(15)

In [168]:
rnge

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [169]:
lspace=np.linspace(1,5,4)

In [170]:
lspace

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [171]:
emp=np.empty((4,6))

In [172]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.86921143e-306, 6.23055651e-307, 8.45593934e-307],
       [7.56593017e-307, 1.11258854e-306, 1.11261502e-306,
        1.42410839e-306, 7.56597770e-307, 6.23059726e-307],
       [1.42419530e-306, 1.11261027e-306, 6.89805151e-307,
        7.56592338e-307, 6.89807188e-307, 1.95819401e-306],
       [1.11261502e-306, 8.45559303e-307, 1.06811422e-306,
        1.05694828e-307, 1.42410974e-306, 8.45528067e-307]])

In [173]:
emp_like=np.empty_like(lspace)

In [174]:
emp_like

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [175]:
ide=np.identity(45)

In [176]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [177]:
ide.shape

(45, 45)

In [178]:
arr=np.arange(99)

In [179]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [180]:
arr=arr.reshape(3,33)

In [181]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [182]:
arr=arr.ravel()

In [183]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

# Numpy Axis

In [184]:
x=([[1,2,3],[4,5,6],[9,0,7]])

In [185]:
arr=np.array(x)

In [186]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [9, 0, 7]])

In [187]:
arr.sum(axis=0)

array([14,  7, 16])

In [188]:
arr.sum(axis=1)

array([ 6, 15, 16])

#Attributes and methods of array

In [189]:
arr.T

array([[1, 4, 9],
       [2, 5, 0],
       [3, 6, 7]])

In [190]:
arr.flat

In [191]:
for items in arr.flat:
    print(items)

1
2
3
4
5
6
9
0
7


In [192]:
arr.ndim # number of dimesnsions

2

In [193]:
arr.size

9

In [194]:
# how much space your arr consuming this tell by nbytes function in bytes
arr.nbytes

72

In [195]:
# one dimentionsal Array
one=np.array([11,22,33,44,55])

In [196]:
one

array([11, 22, 33, 44, 55])

In [197]:
one.argmax().item()# in which index your maximum elemtnt is

4

In [198]:
one.argmin()

np.int64(0)

In [199]:
# this fuction gives the index that if you arrange it like them you git sorted array
one.argsort()

array([0, 1, 2, 3, 4])

In [200]:
arr.argmin() # inTwo D array

np.int64(7)

In [201]:
arr.argmax()

np.int64(6)

In [202]:
# methods using According to axis
arr.argmax(axis=0)

array([2, 1, 2])

In [203]:
arr.argmin(axis=1)

array([0, 0, 1])

In [204]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [9, 0, 7]])

In [205]:
arr.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [1, 2, 0]])

In [206]:
arr.ravel()

array([1, 2, 3, 4, 5, 6, 9, 0, 7])

In [207]:
arr=arr.reshape(3,3)

# Mathematically operations

In [208]:
arr2=np.array([[1,2,3],
              [4,4,6],
              [1,8,9]])

In [209]:
arr+arr2

array([[ 2,  4,  6],
       [ 8,  9, 12],
       [10,  8, 16]])

In [210]:
[22,33]+[12,11]

[22, 33, 12, 11]

In [211]:
arr *arr2

array([[ 1,  4,  9],
       [16, 20, 36],
       [ 9,  0, 63]])

In [212]:
np.sqrt(arr)# square root

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [3.        , 0.        , 2.64575131]])

In [213]:
arr2.sum()

np.int64(38)

In [214]:
arr2.max() # min also

np.int64(9)

In [218]:
arr2

array([[1, 2, 3],
       [4, 4, 6],
       [1, 8, 9]])

In [217]:
np.where(arr2>5)

(array([1, 2, 2]), array([2, 1, 2]))

In [219]:
type(np.where(arr2>5))

tuple

In [220]:
# Counting that are non zeros add add the count 
np.count_nonzero(arr2)

9

In [221]:
np.nonzero(arr2)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1, 2]))

In [222]:
arr2

array([[1, 2, 3],
       [4, 4, 6],
       [1, 8, 9]])

In [223]:
arr2[1,2]=0

In [224]:
np.nonzero(arr2)

(array([0, 0, 0, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 0, 1, 2]))

In [ ]:
import sys #checking that why numpy takes less memeory
ch_arr=[0,4,55,2]

In [227]:
py_arr=[0,3,4,5]
sys.getsizeof(1)*len(py_arr)

112

In [229]:
np_arr=np.array(py_arr)
np_arr.itemsize*np_arr.size

32

** Above we can see that how much the difference is varring from normal method and from Using Numpy**

In [231]:
# tolist method is simply convert np.arr into simple list

np_arr.tolist()

[0, 3, 4, 5]