# **WelCome To Numpy tutorial

In [96]:
import numpy as np

In [97]:
myArr=np.array([[3,22,44345,5]], np.int64)

In [98]:
myArr

array([[    3,    22, 44345,     5]])

In [99]:
myArr[0,1].item()

22

In [100]:
myArr.shape

(1, 4)

In [101]:
myArr.dtype

dtype('int64')

In [102]:
myArr[0,3]=11

In [103]:
myArr

array([[    3,    22, 44345,    11]])

# Array Creation : Conversion from other Python Structures

In [104]:
listArray=np.array([[1,2,3],[5,5,6],[7,8,9]])

In [105]:
listArray

array([[1, 2, 3],
       [5, 5, 6],
       [7, 8, 9]])

In [106]:
listArray.dtype

dtype('int64')

In [107]:
listArray.shape

(3, 3)

In [108]:
listArray.size

9

In [109]:
listArray[0,2]=78

In [110]:
listArray

array([[ 1,  2, 78],
       [ 5,  5,  6],
       [ 7,  8,  9]])

In [111]:
np.array({33,44,55})

array({33, 44, 55}, dtype=object)

In [112]:
zeros=np.zeros((2,5))

In [113]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [114]:
zeros.shape

(2, 5)

In [115]:
zeros.dtype

dtype('float64')

In [116]:
rnge=np.arange(15)

In [117]:
rnge

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [118]:
lspace=np.linspace(1,5,4)

In [119]:
lspace

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [122]:
emp=np.empty((4,6))

In [123]:
emp

array([[1.07764726e-311, 1.07764717e-311, 1.07764732e-311,
        1.07764732e-311, 1.07764765e-311, 1.07764765e-311],
       [1.07764766e-311, 1.07764733e-311, 1.07764764e-311,
        1.07764765e-311, 1.07764765e-311, 1.07764765e-311],
       [1.07764765e-311, 1.07764733e-311, 1.07764766e-311,
        1.07764766e-311, 1.07764733e-311, 1.07764733e-311],
       [1.07764765e-311, 1.07764733e-311, 1.07764733e-311,
        1.07764765e-311, 1.07764765e-311, 1.07764733e-311]])

In [124]:
emp_like=np.empty_like(lspace)

In [125]:
emp_like

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [126]:
ide=np.identity(45)

In [127]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [128]:
ide.shape

(45, 45)

In [129]:
arr=np.arange(99)

In [130]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [131]:
arr=arr.reshape(3,33)

In [132]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [133]:
arr=arr.ravel()

In [134]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

# Numpy Axis

In [135]:
x=([[1,2,3],[4,5,6],[9,0,7]])

In [136]:
arr=np.array(x)

In [137]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [9, 0, 7]])

In [138]:
arr.sum(axis=0)

array([14,  7, 16])

In [139]:
arr.sum(axis=1)

array([ 6, 15, 16])

#Attributes and methods of array

In [140]:
arr.T

array([[1, 4, 9],
       [2, 5, 0],
       [3, 6, 7]])

In [141]:
arr.flat

In [142]:
for items in arr.flat:
    print(items)

1
2
3
4
5
6
9
0
7


In [ ]:
arr.ndim # number of dimesnsions

2

In [144]:
arr.size

9

In [145]:
# how much space your arr consuming this tell by nbytes function in bytes
arr.nbytes

72

In [146]:
# one dimentionsal Array
one=np.array([11,22,33,44,55])

In [147]:
one

array([11, 22, 33, 44, 55])

In [149]:
one.argmax().item()# in which index your maximum elemtnt is

4

In [150]:
one.argmin()

np.int64(0)

In [151]:
# this fuction gives the index that if you arrange it like them you git sorted array
one.argsort()

array([0, 1, 2, 3, 4])

In [152]:
arr.argmin() # inTwo D array

np.int64(7)

In [153]:
arr.argmax()

np.int64(6)

In [154]:
# methods using According to axis
arr.argmax(axis=0)

array([2, 1, 2])

In [155]:
arr.argmin(axis=1)

array([0, 0, 1])

In [156]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [9, 0, 7]])

In [157]:
arr.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [1, 2, 0]])